*** Script1
exception(SyntaxError: Unexpected end of script)
finished(undefined)
*** Script2
exception(SyntaxError: Unexpected identifier 'hoge'. Expected a ';' following a return statement.)
finished(undefined)
testError : OK
*** context.runScript
finished(undefined)
*** context.callFunction
finished(2.3)
testObject : OK
finished(undefined)
finished(undefined)
1: isExecuting=false, isFinished=true
2: isExecuting=false, isFinished=true
testOperation : OK
class ExitError extends Error {
  constructor(code){
    self.errorCode = code ; 
  }
}
Compile ... OK
testCompiler : OK
SUMMARY: OK
